schema: "classroom50/repo-config/v1"
classroom: "pw-a26"
assignment: "gsap"
owner:
  username: "ElliotSchmit"
  id: 179408837
  accepted_at: "2026-09-18T17:37:58Z"
source:
  owner: "tim-cw"
  owner_id: 97471838
  repo: "tpl_gsap"
  branch: "main"
